default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: uchenna4A3@
  host: localhost

development:
  <<: *default
  database: Blog_App_development

  #host: localhost

test:
  <<: *default
  database: Blog_App_test


production:
  <<: *default
  database: Blog_App_production
  username: Blog_App
  password: <%= ENV["BLOG_APP_DATABASE_PASSWORD"] %>

#start

